/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_li_sheldon_ffmpeg4android_FFmpegNative */

#ifndef _Included_com_li_sheldon_ffmpeg4android_FFmpegNative
#define _Included_com_li_sheldon_ffmpeg4android_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_li_sheldon_ffmpeg4android_FFmpegNative
 * Method:    ffmpeg_h264
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_li_sheldon_ffmpeg4android_FFmpegNative_ffmpeg_1h264
  (JNIEnv *, jobject, jint);
  
 
  

#ifdef __cplusplus
}
#endif
#endif
